### ISSUE TITLE
Комментарии к заявке

### ISSUE THREAD

**Issue by aakuptsov** [philmol280/prediction_IT#1]
1. К рассмотрению принимаются только заявки на ГитХабе, оформленные в соответствии с требованиями

2. >>Прежде всего это консольная программа

Никакая часть проекта не может быть консольной. 

3. >>выдаёт предполагаемую цену на основе предсказания алгоритмов машинного обучения. 

К защите не могут быть допущены подобные проекты. Проблема в том, что у нас нет возможности проводить лонгитюдное тестирование и выяснять, насколько точно предсказывают цены твой продукт. На защите продукт необходимо продемонстрировать "здесь и сейчас". 

Думаю, для проекта нужно взять что-то другое или существенно переработать заявку.

**Comment by philmol280** [comment]
Это что-то среднее, между проектом и Исследованием. Проверка на точность и выбор модели это исследовательская часть, результаты которой будут приложены на защите, однако, так как по итогу предполагается интерфейс для работы с этой программой, это будет полноценный продукт в виде сайта. Поэтому я составил заявку, как IT проект, а не исследование. Вы считаете, что лучше будет переписать заявку, как IT исследование? Под консольной программой подразумевалось, что основная работа заключается не в автоматизации и настройке сайта, а в алгоритмах и их отборе. Гит оформлю.

**Comment by aakuptsov** [comment]
>>Это что-то среднее, между проектом и Исследованием.

Увы, друг, у нас так нельзя: либо проект, либо исследование. 

>>так как по итогу предполагается интерфейс для работы с этой программой, это будет полноценный продукт в виде сайта

Понимаю, но всё-таки какова твоя цель: ответить на вопрос? (тогда это исследование) или сделать интерфейс? (тогда это проект) Интерфейс представляется слишком простым делом в данном случае, чтобы быть проектом. Дальше у нас пойдут пользовательские сценарии, там нужно будет 7 сценариев по 7 шагов, я не уверен, что это будет легко написать. 

Рекомендую подумать о переходе на ИТ-исследование. Для исследования также можно написать интерфейс, но защищать ты будешь именно сравнение моделей. 

Кстати, вопрос, как именно проверять эффективность твоей модели, остался без ответа :)

**Comment by philmol280** [comment]
Ок, тогда я переформирую заявку, как IT исследование. Точность модели проверяется стандартным методом машинного обучения - тренируем на одних данных, проверяем точность на других (например обучение проводится на всех кварталах до 15 года, а тесты на период с 15 по 21. На этих данных уже считать среднее квадратичное отклонение, recall и.т.д)

**Comment by aakuptsov** [comment]
>>Ок, тогда я переформирую заявку, как IT исследование.

Ок. 

>>тренируем на одних данных, проверяем точность на других (например обучение проводится на всех кварталах до 15 года, а тесты на период с 15 по 21.

Also ok.
